package Model;

public enum Elements {
    USECASE, EXTENSIONPOINT, ACTOR, UMLSYSTEM, GENERALIZATION, ASSOCIATION, CONDITIONRELATION, NOTE, EXTENDS, INCLUDES, UNKNOWNELEMENT, RELATION, AGGREGATION, ATTRIBUT, CLASS, COMPOSITION, DIAGRAM, DEPENDENCY, IMPLEMENTS, INHERITANCE, METHOD, NONHUMANACTOR, UNKNOWNRELATION, USE
}
