package Control.Strategy.ClassStrategy.Control;

public enum ErrorTypes {
    RELATIONMISSMATCHBINARY, RELATIONMISSMATCHIMPLEMENTS, RELATIONMISSMATCHINHERITANCE, NODISTINCTNAME, NONAME, UNKNOWNRELATION, UNKNOWNTYPECON
}
