package Control.Strategy.ClassStrategy.Control;

public enum ErrorTypes {
    RELATIONMISSMATCHBIN, RELATIONMISSMATCHIMPLEMENTS, RELATIONMISSMATCHINHERITANCE, NODISTINCTNAME, NONAME, UNKNOWNRELATION, UNKNOWNTYPECON
}
