package Control.Visitor;

public enum ErrorTypes {
    ENTITYNAME, SYSTEMNAME, ACTORNAME, USECASENAME, ACTORSCONTAINED, NONBINARYRELATION, NONBINARYASSOCIATION,
    NONBINARYEXTENDS, NONBINARYINCLUDES, NONBINARYGENERALIZATION, EMPTYEXTENSIONPOINT, BINARYCONDITIONRELATION,
    NOTSAMETYPERELATION, SAMETYPERELATION
}
