/*
@author mkowol2s
 */

package Control.Strategy.UseCaseStrategy.DTO;

public enum ErrorTypes {
    ENTITYNAME, SYSTEMNAME, ACTORNAME, USECASENAME, ACTORSCONTAINED, NONBINARYRELATION, NONBINARYASSOCIATION,
    NONBINARYEXTENDS, NONBINARYINCLUDES, NONBINARYGENERALIZATION, EMPTYEXTENSIONPOINT, BINARYCONDITIONRELATION,
    NOTSAMETYPEASSOCIATION, NOTSAMETYPEINCLUDES, NOTSAMETYPEEXTENDS, NOTSAMETYPEGENERALIZATION, EMPTYNOTE,
    CONDITIONRELATIONNONOTE, WRONGBASEUSECASE, TOTALERRORS, UNKNOWNELEMENT
}
